# Generated by Django 4.2.3 on 2023-07-23 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uruntakipmodel',
            table='tablo_uruntakip',
        ),
    ]
